CREATE DATABASE CASESTUDY;
USE CASESTUDY;

DROP TABLE IF EXISTS CDW_SAPP_D_TIME;

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_D_TIME
(TIMEID VARCHAR(8),
DAY DECIMAL(2,0),
MONTH DECIMAL(2,0),
QUARTER VARCHAR(8),
YEAR DECIMAL(4,0)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/TimeID';
