DROP TABLE IF EXISTS TEMP_CDW_SAPP_F_CREDIT_CARD;

CREATE EXTERNAL TABLE IF NOT EXISTS TEMP_CDW_SAPP_F_CREDIT_CARD
(TRANSACTION_ID DECIMAL(9,0),
CUST_CC_NO VARCHAR(16),
TIMEID VARCHAR(8),
CUST_SSN DECIMAL(9,0),
BRANCH_CODE DECIMAL(10,0),
TRANSACTION_TYPE VARCHAR(30),
TRANSACTION_VALUE DECIMAL(20,3)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/CreditCard';

-- set hive.exec.dynamic.partition=true;
-- set hive.exec.dynamic.partition.mode=nonstrict;

DROP TABLE CDW_SAPP_F_CREDIT_CARD;

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_F_CREDIT_CARD
(TRANSACTION_ID DECIMAL(9,0),
CUST_CC_NO VARCHAR(16),
TIMEID VARCHAR(8),
CUST_SSN DECIMAL(9,0),
BRANCH_CODE DECIMAL(10,0),
TRANSACTION_VALUE DECIMAL(20,3)
)
PARTITIONED BY (TRANSACTION_TYPE VARCHAR(30))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/PartitionedCreditCard';

INSERT INTO TABLE CDW_SAPP_F_CREDIT_CARD
PARTITION (TRANSACTION_TYPE)
SELECT TRANSACTION_ID,
CUST_CC_NO,
TIMEID,
CUST_SSN,
BRANCH_CODE,
TRANSACTION_VALUE,
TRANSACTION_TYPE
FROM TEMP_CDW_SAPP_F_CREDIT_CARD;
